### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by LitoMore** [maticzav/ink-table#35]
Could you release the 2.0 version of `ink-table`? Thanks!

I'm working on a migration for [Tink](https://github.com/npm/tink).

Related to this issue: https://npm.community/t/tink-new-search-ui/3087

**Comment by LitoMore** [comment]
I created an issue for tracking width calculation feature: https://github.com/maticzav/ink-table/issues/34.

Maybe we need more discussion for this feature.

**Comment by maticzav** [comment]
Ah yes, there's a problem with the setup. It should have auto published the package.

**Comment by maticzav** [comment]
@LitoMore I manually made a release of version 2.0. I would be very thankful if you have some spare time if you could help me work on #36. This way, future PRs could get merged more quickly, and the code coverage would be better.
