### ISSUE TITLE
Custom headers misaligns borders

### ISSUE THREAD

**Issue by benfletcher** [maticzav/ink-table#47]
When using the `header` prop, unless the return value happens to have the exact width of the rendered column, the right side border character gets misaligned.

Is there a way to prevent this without knowing in advance how wide the column will be? Or am I doing something wrong?

To be clear, if I just pass through `children` with styling, there's no problem. The issue is if I want custom text headers, like:
```
const Header = () => (
  <Color green>
    New Title
  </Color>
);
```

And, on reflection, I'm guessing I should just modify the data table and reserve the `header` prop for styling? That's a reasonable limitation but was unclear to me in the documentation.

**Comment by maticzav** [comment]
Hey, yeah you are right. That's the current limitation.
