### ISSUE TITLE
Cell value 0 is not printed

### ISSUE THREAD

**Issue by slaweet** [maticzav/ink-table#53]
## Current behaviour

If the cell value is `0`, it is replaced with an empty string:
<img width="858" alt="Screenshot 2019-12-01 at 08 32 27" src="https://user-images.githubusercontent.com/1254342/69911032-98e16b00-1415-11ea-8396-541440cf4621.png">

## Expected behaviour
If the cell value is `0`, it is printed:
<img width="850" alt="Screenshot 2019-12-01 at 08 36 05" src="https://user-images.githubusercontent.com/1254342/69911045-b282b280-1415-11ea-8dd8-e5cfa8643ea5.png">

**Comment by maticzav** [comment]
Thank you for both PRs 🙂
