### ISSUE TITLE
Publish Ink 3.0 compatible version to npm

### ISSUE THREAD

**Issue by radeva** [maticzav/ink-table#65]
Could you publish the latest version to npm? I can see the last version in npm is from an year ago, but the update about supporting Ink 3.0 is implemented in Aug, 2020. 

Thanks!

**Comment by kderbalah** [comment]
Looks like that this is a side-effect of https://github.com/maticzav/ink-table/issues/9

**Comment by maticzav** [comment]
Thank you for pinging me. I've updated NPM token and updated the node version on Travis. I hope it passes.

**Comment by draconisNoctis** [comment]
The latest version is still a year old

**Comment by maticzav** [comment]
Published, thank you for your patience. it's now TypeScript compatible.
